### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by sunxfancy** [sjlevine/atom-slime#11]
When I installed the last version of Atom and atom-slime, it has the following error, please help me:

/home/sxf/.atom/packages/atom-slime/node_modules/paredit.js/lib/editor.js:465
Hide Stack Trace
TypeError: Cannot read property 'type' of undefined
    at linesToIndent.reduce.idx (/home/sxf/.atom/packages/atom-slime/node_modules/paredit.js/lib/editor.js:465:37)
    at Array.reduce (native)
    at Object.exports.editor.indentRange (/home/sxf/.atom/packages/atom-slime/node_modules/paredit.js/lib/editor.js:446:28)
    at Array.module.exports.newline (/home/sxf/.atom/packages/lisp-paredit/lib/edit-commands.coffee:85:28)
    at atom-text-editor.<anonymous> (/home/sxf/.atom/packages/lisp-paredit/lib/utils.coffee:48:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)

**Comment by sunxfancy** [comment]
It throw errors when I typed a line of lisp code and push the Enter...
OS: Ubuntu 14.04
Atom: 1.41
atom-slime: 2.2.0
lisp-paredit: 0.5.1

**Comment by sjlevine** [comment]
Hello, thanks for reporting the issue! I've narrowed it down to a glitch in a library used by `atom-slime`. Hopefully it will be fixed soon, I've reported it upstream.

**Comment by sjlevine** [comment]
Should be fixed now as of `atom-slime` v2.2.1. 

Also, if you have `lisp-paredit` installed, completely remove it and re-install it.
