### ISSUE TITLE
Failed to activate the atom-slime package

### ISSUE THREAD

**Issue by franchenstein** [sjlevine/atom-slime#27]
Buffer.alloc is not a function
Hide Stack Trace
TypeError: Buffer.alloc is not a function
    at Client.setup_read (/home/kaiser/.atom/packages/atom-slime/node_modules/swank-client-js/lib/client.js:97:17)
    at new Client (/home/kaiser/.atom/packages/atom-slime/node_modules/swank-client-js/lib/client.js:29:8)
    at Object.module.exports.AtomSlime.setupSwank (/home/kaiser/.atom/packages/atom-slime/lib/atom-slime.coffee:72:18)
    at Object.module.exports.AtomSlime.activate (/home/kaiser/.atom/packages/atom-slime/lib/atom-slime.coffee:41:6)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28

**Comment by leizongmin** [comment]
I met the same problem. I am using **Atom v1.8.0** for **Mac**, execute  `process.version` on the Atom Developer Tools window it results `v5.1.1`. It seems there isn't a `Buffer.alloc()` method in this version of Node.js.

The version of **atom-slime** is `v2.4.1`.

**Comment by cbaggers** [comment]
Same as above:
- atom 1.8.0 
- OSX El Capitan

**Comment by sjlevine** [comment]
Hi all,

Thanks for pointing this out! I'll have a fix out shortly, which reverts to the older Buffer API shortly in `swank-client-js`. Evidently the machine I was testing on yesterday has a newer version of Node.

**Comment by haz** [comment]
@sjlevine That makes me a little concerned for atom stability then if the same version of atom can use different node.js versions. There a way to force a particular node version for the plugin? Maybe that's all that's required...

**Comment by sjlevine** [comment]
I figured it out: I was testing against Atom beta v1.9, and I didn't realize older versions of Node.js (as shipped in the current v1.8) don't support the newer Buffer API. 

I think for now porting back to the old API is fine, but sometime soon, after v1.9 is the main non-beta release, I can make this change and the corresponding dependency changes in the package.json files that should fix this I believe.

**Comment by sjlevine** [comment]
I agree it's not ideal, but at least that should fix people's bugs for now without requiring everyone to update Atom!

**Comment by sjlevine** [comment]
Ok, should be fixed in the latest version of atom-slime - 2.4.2. Thanks all!

**Comment by haz** [comment]
Ah, well that's fine. As long as the node.js version is tied to the atom version, then there shouldn't be too much headache. Does the old api still work with atom v1.9? Thanks for the quick fix!

**Comment by sjlevine** [comment]
Yep, just tested against the current v1.8 and beta v1.9 - the old API works (though is technically deprecated in the new one). I've made a new issue in `swank-client-js` to remind myself to port back to the newer API once things settle down :-)

**Comment by leizongmin** [comment]
Thanks for the quick fix!
