### ISSUE TITLE
Uncaught TypeError: Cannot read property 'connected' of undefined

### ISSUE THREAD

**Issue by andriypuhach** [sjlevine/atom-slime#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Linux Mint
**Thrown From**: [atom-slime](https://github.com/sjlevine/atom-slime) package, v1.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'connected' of undefined

```
At /home/andrew/.atom/packages/atom-slime/lib/slime-autocomplete.coffee:11

TypeError: Cannot read property 'connected' of undefined
  at Object.module.exports.getSuggestions (/home/andrew/.atom/packages/atom-slime/lib/slime-autocomplete.coffee:16:14)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```

### Commands

```
     -5:10.8.0 core:save (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -3:29.9.0 lisp-paredit:newline (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -3:28.7.0 lisp-paredit:delete-backwards (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -3:27.9.0 core:save (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -2:09.2.0 lisp-paredit:newline (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -2:07.2.0 core:save (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -2:06.3.0 lisp-paredit:delete-backwards (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -2:05.1.0 core:save (atom-text-editor.editor.lisp-paredit-strict.is-focused)
  6x -0:13.6.0 lisp-paredit:delete-backwards (atom-text-editor.editor.lisp-paredit-strict.is-focused)
  2x -0:07.6.0 core:select-left (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -0:06.6.0 lisp-paredit:delete-backwards (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -0:05.5.0 core:move-right (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -0:04.7.0 lisp-paredit:delete-backwards (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -0:01.5.0 core:move-left (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -0:01.2.0 core:move-right (atom-text-editor.editor.lisp-paredit-strict.is-focused)
     -0:00.1.0 lisp-paredit:delete-backwards (atom-text-editor.editor.lisp-paredit-strict.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-slime, v1.7.1
autocomplete-ruby, v0.1.0
javascript-snippets, v1.0.0
language-conky, v0.2.0
language-ejs, v0.2.0
language-lisp, v0.1.2
language-lua, v0.9.4
linter, v1.5.0
linter-lua, v1.0.0
linter-ruby, v1.1.1
lisp-paredit, v0.4.6
node-debugger, v1.1.8
nodejs-snippets, v1.0.2

# Dev
No dev packages
```

**Comment by sjlevine** [comment]
Hello @andriypuhach, thanks for bug report. I believe this should be fixed!
