### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by nimmividya** [sjlevine/atom-slime#67]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-slime](https://github.com/sjlevine/atom-slime) package 2.8.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:392

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:321:63)
    at BufferedProcess.start (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:127:20)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:112:18)
    at SwankStarter.module.exports.SwankStarter.start (/packages/atom-slime/lib/swank-starter.coffee:24:16)
    at Object.swankStart (/packages/atom-slime/lib/atom-slime.coffee:102:17)
    at Object.activate (/packages/atom-slime/lib/atom-slime.coffee:85:8)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:255:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
atom-slime 2.8.0 
language-common-lisp 0.9.5 
language-lisp 0.2.0 
lisp-paredit 0.6.0 
```

**Comment by IamandIr1** [comment]
@nimmividya, do you mind providing any insights as to how you were able to resolve this error?

**Comment by neil-lindquist** [comment]
I haven't had this error, but in Atom-Slime's settings have you tried using the full path to your lisp executable?  And have do you have the Slime Path set to the slime directory?
If those don't work, maybe you can share what your lisp, OS, atom version, slime version, ect.  That might give some incite on what to look for solutions.
