### ISSUE TITLE
Uncaught RangeError: out of range index

### ISSUE THREAD

**Issue by TeamSPoon** [sjlevine/atom-slime#84]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-slime](https://github.com/sjlevine/atom-slime) package 2.8.0

### Stack Trace

Uncaught RangeError: out of range index

```
At buffer.js:602

RangeError: out of range index
    at Buffer.copy (buffer.js:602:18)
    at Client.socket_data_handler (/packages/atom-slime/node_modules/swank-client-js/lib/client.js:89:25)
    at /packages/atom-slime/node_modules/swank-client-js/lib/client.js:71:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
  2x -3:57.4.0 slime:connect (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-eclipse-syntax 0.0.6 
atom-emacs-calc 1.2.0 
atom-jade 0.3.0 
atom-repl 0.1.0 
atom-slime 2.8.0 
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.5.8 
browse 1.10.8 
build 0.70.0 
busy-signal 2.0.1 
ctrl-dir-scroll 0.2.5 
dev-tools-themes 0.1.3 
intentions 1.1.5 
keymap-display 0.15.0 
language-autolisp 1.1.0 
language-autolisp-dtgoitia 2.0.0 
language-common-lisp 0.9.5 
language-emacs-lisp 1.3.0 
language-lisp 0.2.0 
language-newlisp 0.3.0 
language-oftlisp 0.0.4 
language-prolog 0.11.0 
language-scheme 1.4.0 
language-slim 1.0.0 
language-sugly 1.0.1 
linter 2.3.0 
linter-prolog 0.2.0 
linter-slime-lint 0.3.1 
linter-ui-default 1.7.1 
lisp-paredit 0.6.0 
minimap 4.29.9 
multi-cursor 2.1.5 
mypddl 1.0.0 
parinfer 1.23.0 
proto-repl 1.4.24 
proto-repl-charts 0.4.1 
proto-repl-sayid 0.1.4 
satisfy-dependencies 0.4.2 
scheme-syntax 0.4.0 
set-syntax 0.4.0 
slima 1.3.0 
styri-syntax 1.0.0 
sublime 0.5.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.5 
sublime-word-navigation 0.2.1 
sublimify 0.10.0 
tag 0.5.0 
teletype 0.13.3 
text-manipulation 0.6.0 
```

**Comment by neil-lindquist** [comment]
So, atom-slime isn't currently actively maintained.  I'm noticing that you have both atom-slime and SLIMA installed; I should probably document it better but because SLIMA is a fork of atom-slime they aren't designed to coexist.  Does this still occur if you have atom-slime disabled/uninstalled?  If it does, what steps did you take to get here?
